export enum errorCodesGql {
    GRAPHQL_PARSE_FAILED= 'GRAPHQL_PARSE_FAILED',
    GRAPHQL_VALIDATION_FAILED = 'GRAPHQL_VALIDATION_FAILED',
    BAD_USER_INPUT = 'BAD_USER_INPUT',
    UNAUTHENTICATED = 'UNAUTHENTICATED',
    FORBIDDEN = 'FORBIDDEN',
    PERSISTED_QUERY_NOT_FOUND = 'PERSISTED_QUERY_NOT_FOUND',
    PERSISTED_QUERY_NOT_SUPPORTED = 'PERSISTED_QUERY_NOT_SUPPORTED',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
